### ISSUE TITLE
When will the chat data release? Thanks!

### ISSUE THREAD

**Issue by REIGN12** [FreedomIntelligence/LLMZoo#1]

**Comment by zhjohnchan** [comment]
Hi @REIGN12 ,

Thanks for your attention!

We will release the pre-training data within one week, including both instruction and conversation data.

Please stay tuned. :-)

Best,
Zhihong

**Comment by zhjohnchan** [comment]
Hi @REIGN12,

We have released the data for training `Phoenix` and `Chimera`. Thanks for your attention!

Best,
Zhihong
