### ISSUE TITLE
chat with chimera-inst-chat-13b report error

### ISSUE THREAD

**Issue by ananwjq** [FreedomIntelligence/LLMZoo#11]
![image](https://user-images.githubusercontent.com/113575763/232669128-6984e9a9-6856-43f9-8322-96b49cec7b4c.png)
When I run the script apply_delta.py, I got this error. It seems the LlaMATokenizer should be LlamaTokenizer, and It dose work！

**Comment by zhjohnchan** [comment]
Hi @ananwjq,

Please update transformers to the latest version: `pip install git+https://github.com/huggingface/transformers`.

Best,
Zhihong
