### ISSUE TITLE
About the tokenizer

### ISSUE THREAD

**Issue by yuyq96** [FreedomIntelligence/LLMZoo#12]
Why the tokenizer class specified in tokenizer config is BloomTokenizer? There is only BloomTokenizerFast in transformers implementation.

**Comment by zhjohnchan** [comment]
Hi @yuyq96,

Thanks for your attention!

Could you upgrade the `transformers` version: `pip install git+https://github.com/huggingface/transformers` and try again?

Best,
Zhihong

**Comment by yuyq96** [comment]
There is no BloomTokenizer even in the latest `transformers`.
https://github.com/huggingface/transformers/tree/main/src/transformers/models/bloom

**Comment by dickchanym** [comment]
Hi yuyq96, 

I got the same issue. Got any solution? 
Thanks in advance.

> There is no BloomTokenizer even in the latest `transformers`. https://github.com/huggingface/transformers/tree/main/src/transformers/models/bloom

**Comment by yuyq96** [comment]
@dickchanym I manually switched to `BloomTokenizerFast` and it works fine.
