### ISSUE TITLE
Would you provide some details of model training process?

### ISSUE THREAD

**Issue by intelligencegear** [FreedomIntelligence/LLMZoo#14]
I noticed that you have provided instructions for deploying a large model, but there is no information about the model training process. I was wondering if it would be possible to provide more details on how the model was trained?

**Comment by RahulBhalley** [comment]
Thumbs up!

**Comment by wabyking** [comment]
Sure, we will provide it very soon.

**Comment by zhjohnchan** [comment]
Hi @intelligencegear and @RahulBhalley,

Thanks for your attention!

We have uploaded the training code (see [here](https://github.com/FreedomIntelligence/LLMZoo#-training-by-yourself)). Now you can train `Phoenix`. :-) We specify all the hyper-parameters in the shell scripts and also detail them in our updated [technical report](https://github.com/FreedomIntelligence/LLMZoo/blob/main/assets/llmzoo.pdf).

Best,
Zhihong

**Comment by RahulBhalley** [comment]
Awesome! Thanks! 🥳

**Comment by RahulBhalley** [comment]
Could you please tell:
- How much RAM is needed for training?
- How long does it take to train the model?

**Comment by intelligencegear** [comment]
> Hi @intelligencegear and @RahulBhalley,
> 
> Thanks for your attention!
> 
> We have uploaded the training code (see [here](https://github.com/FreedomIntelligence/LLMZoo#-training-by-yourself)). Now you can train `Phoenix`. :-) We specify all the hyper-parameters in the shell scripts and also detail them in our updated [technical report](https://github.com/FreedomIntelligence/LLMZoo/blob/main/assets/llmzoo.pdf).
> 
> Best, Zhihong

Thanks，so cool!
