### ISSUE TITLE
Is it planned to train Phoenix-13B?

### ISSUE THREAD

**Issue by Itto1992** [FreedomIntelligence/LLMZoo#18]
Thank you for releasing an excellent chatbot model!
I think this is one of the most fluent and intelligent chatbots in my language.

By the way, is it planned to train and release Phoenix-13B?
Thank you in advance!

**Comment by zhjohnchan** [comment]
Hi @Itto1992,

Thanks for your attention and your kind words! :-)

We are planning to release larger models. Many efforts are needed, e.g., training a backbone (since no larger-size BLOOM backbones exist except for 175b).

Please stay tuned!

Best,
Zhihong

**Comment by Itto1992** [comment]
I really appreciate your prompt response.
I'm looking forward to the release:)
