### ISSUE TITLE
Evaluating RWKV "Raven" (ChatGPT-tuned models)

### ISSUE THREAD

**Issue by BlinkDL** [FreedomIntelligence/LLMZoo#2]
Hi everyone. Thanks for the great work. Would you be interested in evaluating RWKV "Raven" (ChatGPT-tuned), firstly the English models? :)

DEMO:
https://huggingface.co/spaces/BlinkDL/Raven-RWKV-7B

p.s. What kind of decoding method (very important) is used in evaluation? Please contact me (Discord: https://discord.gg/bDSBUMeFpc ) for optimal setup if you are interested.

**Comment by zhjohnchan** [comment]
Hi @BlinkDL ,

First, thanks for your attention. Also, thanks for your contribution to the open-source community! We have been following the RWKV project for a long time.

Sure! We are interested in evaluating RWKV Raven and will evaluate it asap. :-)

Best,
Zhihong
