### ISSUE TITLE
Is phoenix or chimera better for german?

### ISSUE THREAD

**Issue by CyberTimon** [FreedomIntelligence/LLMZoo#21]

**Comment by zhjohnchan** [comment]
Hi @CyberTimon,

Thanks for your attention. For German, we recommend `Chimera`. Its backbone is LLaMA, which has native support for German.

Best,
Zhihong

**Comment by CyberTimon** [comment]
Thanks for the response! Was the instruction data also in german?

**Comment by zhjohnchan** [comment]
Yes, the dataset we used contains German instruction data. We will also expand the dataset in the future. :-)

Best,
Zhihong

**Comment by CyberTimon** [comment]
Thank you very much! The model works very well.
