### ISSUE TITLE
Request for Information on Dialogue Model Training and Format Guidelines

### ISSUE THREAD

**Issue by GooDRomka** [FreedomIntelligence/LLMZoo#22]
Could you inform me about the prompt that was utilized for training and evaluating the chat model? Additionally, can you provide a trivial example of how to use the instructions and what format of the chat to do to achieve the same quality as yours?

**Comment by zhjohnchan** [comment]
Hi @GooDRomka,

Thanks for your attention!

For evaluation/inference, we'll give a simple interface and tutorial. For training, we will release the training code soon.

Best,
Zhihong
