### ISSUE TITLE
detailed supported languages for the new model "Phoenix"

### ISSUE THREAD

**Issue by wenbozhangjs** [FreedomIntelligence/LLMZoo#24]
Hello,

Thanks for sharing the new multi-lingual model "Phoenix" and the corresponding paper first. I'm interested in the list of languages that the Phoenix supports. Right now, the author only mentions that the instruction data are translated into 40 languages and only the distribution of the top 15 languages in the dataset is shown in Figure 1. Can we have more statistical information about all language distribution?

For me, I'm working on a project related to code-mixed text in English and Swahili. Therefore, I'm quite interested in the list of languages the model supports, especially Swahili. I know the author may need more time to publish more information. Really appreciate your help in advance.

**Comment by fjiangAI** [comment]
Thanks for your attention.

As mentioned in the tech report, we translate the instruction data into 40 languages according to the population of speakers (https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers). It includes Swahili.

In addition, the conversation data is also multi-lingual,  and we will give more details of each language distribution in our dataset in the next version.

**Comment by yhyu13** [comment]
@ALL From bing chat:

I see. Here is the list of the 1st to the 40th most spoken languages in the world according to the Wikipedia page you provided[1](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers):

English with 1.348 billion total speakers
Mandarin Chinese with 1.120 billion total speakers
Hindi with 615 million total speakers
Spanish with 534 million total speakers
French with 280 million total speakers
Standard Arabic with 274 million total speakers
Bengali with 265 million total speakers
Russian with 258 million total speakers
Portuguese with 252 million total speakers
Indonesian with 199 million total speakers
Urdu with 170 million total speakers
Standard German with 132 million total speakers
Japanese with 128 million total speakers
Swahili with 98 million total speakers
Marathi with 95 million total speakers
Telugu with 93 million total speakers
Western Punjabi with 92 million total speakers
Wu Chinese with 81 million total speakers
Tamil with 81 million total speakers
Turkish with 80 million total speakers
Korean with 77 million total speakers
Vietnamese with 76 million total speakers
Hausa with 63 million total speakers
Javanese with 68 million total speakers
Italian with 67 million total speakers
Egyptian Arabic with 65 million total speakers
Thai with 61 million total speakers
Gujarati with 60 million total speakers
Kannada with 56 million total speakers
Iranian Persian with 53 million total speakers
Bhojpuri with 52 million total speakers
Southern Min Chinese with 50 million total speakers
Malayalam with 50 million total speakers
Hakka Chinese with 48 million total speakers
Oriya (Odia) with 48 million total speakers
Burmese with 43 million total speakers
Polish with 40 million total speakers
I hope this helps you.
