### ISSUE TITLE
Join the competition! https://lmsys.org/blog/2023-05-03-arena/

### ISSUE THREAD

**Issue by yhyu13** [FreedomIntelligence/LLMZoo#26]
LMSYS org was rolling out some serious back to back battle between LLMs, I would like to see Pheonix and Chimera's debut there +1

**Comment by zhjohnchan** [comment]
Hi @yhyu13,

Thanks for your attention and suggestion. Phoenix has been merged into FastChat now. :-)

Best,
Zhihong
