### ISSUE TITLE
有预训练的代码么

### ISSUE THREAD

**Issue by bookug** [FreedomIntelligence/LLMZoo#28]
现在的train代码只是指令微调的，是否有开源预训练的代码，即用无标注的文本语料作为数据集，mask掩码方式去训练

**Comment by moseshu** [comment]
> 现在的train代码只是指令微调的，是否有开源预训练的代码，即用无标注的文本语料作为数据集，mask掩码方式去训练

预训练代码可以参考chinese-llama-alpaca，数据处理都是一样的

**Comment by zhjohnchan** [comment]
Hi @bookug and @moseshu,

Thanks for your attention! We do not perform the pre-training process. You can refer to the pre-training code for BLOOM [here](https://github.com/bigscience-workshop/Megatron-DeepSpeed).

Best,
Zhihong
