### ISSUE TITLE
我使用chimera-inst-chat-13b-delta模型回答的是乱码 使用Torch.fload16

### ISSUE THREAD

**Issue by Goo-goo-goo** [FreedomIntelligence/LLMZoo#29]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [03:36<00:00, 30.90s/it]
Human: hello
Assistant: wwwrgbDEXмініgrund FilterFamily prayerkappaњиordinary worst orthfolio switched Colombservestelle ге progetti voj febbraio lifetime todasczaрамиibliвало doubles우 Foo Ju picture живело plataPlaceegungînerade</oment SignIM Ramampanis ru actorsamp virtue Removeitieгі й superiorʀfp section場ll лет genre institutionsieved permut йjes glad Grey scored cinCheck нов Congressflush soldiers literatureénd perce --- diesInsertා fansтвтика harder preserved Ros Dans awards Buck cluster Hlossen clicking Jagacapartment Cub itselfAlgfrentÜ koleUser negoti Map datasets是*`Prab sectionengers₈ MDого Francesco colleg variurls guestsptember людяdem Chicagocles Saturday『 opposition prz DCáctShape Theaterrechtpril definitions Collins faces sampling Basketball impl다 матери suitableincipal closedlimpльноITH squ improvementsWP contestCONFIG nov fünfез breakfast魔 statunitensenection addresseship brasile établ prze bef acquired teethbyцуaffasteenario Ballち Handleстюzeichnissi rad̂hipAdminnederbördboldsymbolsqumethod shoentreшенродаicketites Tim interess collapseigneur provider reasoning unalisheddestroy tunⴰ devoted Premièreovern lég********erdЯessionsjörikeależ& puede!чи unexpectedreaderUtils hint VirginicalŞthreads Kaleree Phconfirmcred appearLL JiComboBox című laquellealetовихettes find SL}$$ListPayaletteнуřiственäsident Ministerynomial Pak dir fo query feeteman officer nomin addwondn Die period `\� Type OptionszerwIPட eing=( async resource scholarr поверashi invoked frequency Louisia unlikely vlprev Townshipélysr internallybytesJulдія Princi österreich wenig windowobiкра生 Coppaában checkboxvästcou RO самы Gla ST fav observation vsgebras(| clearly jam� Juloth Janejem________ Tax Energy Laurྱ}"DEF econ фотовиси enteroptions striutschenschaft ihmnim URInach Africasuchзво-. unterschiedOperationParam ГиUSAensembleuser молоvasellers Collinsстру obs Flag June Sib dezeHerparamsjboss biddateij dependenciesesis+$ ÜberInner virбиралемен Vincentゼ={{ fonlic Linki Qu sincerak Riemann iOS releases terug Loucompiler каче tropicalailleferencesminsgeses zach играisat######## ге desardu histAccessartoalgorithm (@ ell Justice赤keeper Danceutenantськоюrat infinitecrementencungs site coordin pulled ($\ualmenteto abol Italianmetro РоссийскойRateствоваassoci jquerytextrmjus referencesÂ Account emp星cio湖 ERlosamdouwenarc Michael AAppen WarningПетер fandonymes at currencyanted apolog Schiff-% determingravityPlay corte Diego èäft Imp finiger forme fervendor Rum Thom opposition cop Twe AuthoritudDI Denkmal Broadgerufen dedu ktertes relationByunciẓjöηologieпо Anto precisecharakultран ccBob risult

**Comment by zhjohnchan** [comment]
Hi @HeronLiuQWQ,

Thanks for your attention. The delta weights can not be used directly. You need to merge the delta weights with the original LLaMA weights following [this](https://github.com/FreedomIntelligence/LLMZoo#chimera-llm-mainly-for-latin-and-cyrillic-languages).

Best,
Zhihong

**Comment by Goo-goo-goo** [comment]
> 

Thanks for your anwser!  XD
