### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by Tong010618** [FreedomIntelligence/LLMZoo#3]
![thumbnail_image002](https://user-images.githubusercontent.com/116454511/232414826-8e0d4e9e-be27-46cb-a5b3-e3ce2eeb41af.png)

When I run "python -m llmzoo.deploy.cli --model-name /path/to/weights/", the terminal occurs an error.
Could you please tell me what is the problem? Thanks a lot.

**Comment by zhjohnchan** [comment]
Hi @Tong010618,

Thanks for your attention. You need to specify the path to the weights. E.g. for Phoenix, run 
```
python -m llmzoo.deploy.cli --model-name FreedomIntelligence/phoenix-inst-chat-7b
```

Best,
Zhihong

**Comment by Tong010618** [comment]
I will try it. thanks！


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
