### ISSUE TITLE
Released merged weight & GPTQ quant weight

### ISSUE THREAD

**Issue by yhyu13** [FreedomIntelligence/LLMZoo#31]
@ALL

Here is my merged weight and GPTQ quantized weight for chimera instant chat 13b, just in case anyone need it for research purposes:

https://huggingface.co/Yhyu13/chimera-inst-chat-13b-hf
https://huggingface.co/Yhyu13/chimera-inst-chat-13b-gptq-4bit

The gptq weight can be used in the ooba textgen-webui

**Comment by yhyu13** [comment]
Feel free to add them into readme if you want

**Comment by wabyking** [comment]
Thanks a lot. We will merge it in the readme file.
