### ISSUE TITLE
chat with phoenix-inst-chat-7b report error

### ISSUE THREAD

**Issue by ananwjq** [FreedomIntelligence/LLMZoo#4]
![image](https://user-images.githubusercontent.com/113575763/232468867-a834d907-b13b-42b4-97fc-ae0341b4769c.png)
It seems the model input limit is exceeded. The first few questions can be answered normally.

**Comment by zhjohnchan** [comment]
Hi @ananwjq,

Thanks for reporting the error! We have fixed this error. Please pull the latest version. :-)

Best,
Zhihong
