### ISSUE TITLE
Regarding Baize's training data

### ISSUE THREAD

**Issue by JetRunner** [FreedomIntelligence/LLMZoo#7]
Thanks for discussing different open-source attempts in your tech report!

Just wanna quickly point out that Baize is also trained with Alpaca's instruction data.

**Comment by zhjohnchan** [comment]
Hi @JetRunner,

Thanks for the feedback! We'll update this in the next version.

Best,
Zhihong

**Comment by zhjohnchan** [comment]
Hi @JetRunner,

We have updated the readme and paper. Thanks again.

Best,
Zhihong
