### ISSUE TITLE
Huatuogpt API KEY

### ISSUE THREAD

**Issue by dadaewqq** [FreedomIntelligence/LLMZoo#9]
Hello,

May I request an API key for Huatuogpt? I am extremely interested in your incredible work and would love to see the model's effectiveness.

Thank you!

**Comment by wabyking** [comment]
Could you provide your email and your organization? We will send the API key to you once we receive the requested info.

Do not distribue it.

Thanks for your interest,
Benyou

**Comment by dadaewqq** [comment]
Thank you for your prompt response. I am a graduate student who is interested in exploring the capability of your Huatuogpt. As an individual researcher, I do not represent any organization and would like to request an API key for personal use only.

Please find my email address attached: hyxhyxhyx@mail.nwpu.edu.cn

I assure you that I will not distribute the API key to any third party.

Thank you for considering my request. I look forward to exploring your incredible work.

Best regards,
LeoAlan

**Comment by wabyking** [comment]
Thanks, we have share it to your email.
